REM Script require value for DBID, INSTNACE_NUMBER and SQL_TEXT
REM DBID -  SELECT DBID FROM V$DATABASE;
REM INSTANCE_NUMBER - SELECT INSTANCE_NUMBER FROM V$INSTANCE;
  SELECT 
  STAT.SQL_ID, 
  SQL_TEXT,
  PLAN_HASH_VALUE, 
  PARSING_SCHEMA_NAME, 
  ELAPSED_TIME_DELTA, 
  STAT.SNAP_ID, 
  SS.END_INTERVAL_TIME 
FROM 
  DBA_HIST_SQLSTAT STAT, 
  DBA_HIST_SQLTEXT TXT, 
  DBA_HIST_SNAPSHOT SS 
WHERE 
  STAT.SQL_ID = TXT.SQL_ID AND 
  STAT.DBID = TXT.DBID AND 
  SS.DBID = STAT.DBID AND 
  SS.INSTANCE_NUMBER = STAT.INSTANCE_NUMBER AND 
  STAT.SNAP_ID = SS.SNAP_ID AND 
  STAT.DBID = (SELECT DBID FROM V$DATABASE) AND 
  STAT.INSTANCE_NUMBER = (SELECT INSTANCE_NUMBER FROM V$INSTANCE) AND 
  UPPER(SQL_TEXT) LIKE 'SELECT .....'
ORDER BY 
  ELAPSED_TIME_DELTA DESC
